## DAY 6 - DATA MANIPULATION

Data Manipulation means working with data - reading it, exploring it, cleaning it, filtering it, combining it and summarizing it.

We use two main libraries for this:
- numpy  : for numerical operations
- pandas : for working with tables of data (DataFrames)

In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

## LOADING DATA

We use pd.read_csv() to load a CSV file into a DataFrame.

A DataFrame is basically a table with rows and columns, just like an Excel sheet.

We are using the Titanic dataset here which has passenger information like name, age, sex, fare, survival status etc.

In [4]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## HEAD AND TAIL

head() gives you the first n rows of the dataframe.
By default it gives 5 rows. You can pass a number inside to get that many rows.

This is useful when you want to quickly see what the data looks like without printing the entire dataset.

In [5]:
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

tail() gives you the last n rows of the dataframe.
It is useful to check if the data loaded properly till the end.

In [6]:
titanic.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## SHAPE, COLUMNS AND INFO

shape gives you the dimensions of the dataframe as (rows, columns).

columns gives you the list of all column names.

info() gives you a summary - column names, non-null counts and data types.

In [7]:
# number of rows and columns
titanic.shape

(891, 12)

In [8]:
# display all column names
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [9]:
# gives column names, data types and null counts
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

## DATA TYPES

dtypes tells you the data type of each column.

Common data types you will see:
- int64   : whole numbers
- float64 : decimal numbers
- object  : text / string columns
- bool    : True or False values

Knowing the data type is important because you cannot do math on text columns.

In [10]:
# data types of all columns
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

You can compare dtypes to a specific type to get a boolean result (True/False) for each column.

This tells you which columns are of type object.

In [11]:
# returns True for columns that are of type object
titanic.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

You can use that boolean mask to filter and show only the object type columns.

In [12]:
# shows only the columns that have object data type
titanic.dtypes[titanic.dtypes == "object"]

Series([], dtype: object)

## DESCRIPTIVE STATISTICS

describe() gives you a statistical summary of all numeric columns.

It shows:
- count  : number of non-null values
- mean   : average
- std    : standard deviation (how spread out the values are)
- min    : minimum value
- 25%    : first quartile
- 50%    : median
- 75%    : third quartile
- max    : maximum value

This is one of the first things you should run when you load a new dataset.

In [13]:
# describes how the data is distributed
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

You can also run describe on a specific column to see the stats for just that one column.

In [14]:
# describes a particular column
titanic['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

You can also use individual functions directly on a column.

In [15]:
# returns the maximum value of the column
titanic['Age'].max()

np.float64(80.0)

In [16]:
# returns the minimum value
titanic['Age'].min()

np.float64(0.42)

In [17]:
# returns the average value
titanic['Age'].mean()

np.float64(29.69911764705882)

In [18]:
# returns the sum of all values
titanic['Age'].sum()

np.float64(21205.17)

## SELECTING COLUMNS

You can select a single column using df['column_name'].
This returns a Series (like a single column).

To select multiple columns, pass a list of column names inside double brackets df[['col1', 'col2']].
This returns a DataFrame.

In [19]:
# select a single column - returns a Series
titanic['Survived']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [20]:
# select multiple columns - returns a DataFrame
titanic[['Name', 'Age', 'Sex']]

                                                  Name   Age     Sex
0                              Braund, Mr. Owen Harris  22.0    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                               Heikkinen, Miss. Laina  26.0  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                             Allen, Mr. William Henry  35.0    male
..                                                 ...   ...     ...
886                              Montvila, Rev. Juozas  27.0    male
887                       Graham, Miss. Margaret Edith  19.0  female
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  female
889                              Behr, Mr. Karl Howell  26.0    male
890                                Dooley, Mr. Patrick  32.0    male

[891 rows x 3 columns]

## UNIQUE VALUES AND NULL CHECK

unique() gives you all the distinct values present in a column.
This is very useful for categorical columns like Cabin, Embarked, Sex etc.

isnull() checks for missing values. When combined with sum() it tells you how many nulls are in each column.

In [21]:
# unique gives all the unique values from the column
titanic['Cabin'].unique()

<StringArray>
[          nan,         'C85',        'C123',         'E46',          'G6',
        'C103',         'D56',          'A6', 'C23 C25 C27',         'B78',
 ...
        'B102',         'B69',         'E49',         'C47',         'D28',
         'E17',         'A24',         'C50',         'B42',        'C148']
Length: 148, dtype: str

In [22]:
# isnull checks for null values, sum counts them per column
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

np.where() can be used to find the exact row indices where null values exist in a column.

In [23]:
# find the row indices where Age has null values
np.where(titanic['Age'].isnull() == True)

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888]),)

## ADDING A NEW COLUMN

You can add a new column to a dataframe simply by assigning a value to a new column name.

If you assign a single value, that value gets repeated for every row.
If you assign an expression using other columns, it calculates row by row.

In [24]:
# adding a column with a constant value
titanic['message'] = 'LetsGoooo'
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,message
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,LetsGoooo
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,LetsGoooo
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,LetsGoooo
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,LetsGoooo
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,LetsGoooo

## PANDAS SERIES

A Series is a 1-dimensional structure in Pandas.
Think of it as a single column with an index attached to each value.

When you select one column from a DataFrame, you get a Series back.

In [25]:
# creating a basic Series with default index (0, 1, 2, 3)
marks = pd.Series([80, 90, 70, 95])
marks

0    80
1    90
2    70
3    95
dtype: int64

You can also create a Series with a custom index instead of the default 0, 1, 2.
This makes it easy to label your data meaningfully.

In [26]:
# Series with custom index
marks = pd.Series(
    [80, 90, 70],
    index=['Lahari', 'Bharathi', 'Pranav']
)
marks

Lahari      80
Bharathi    90
Pranav      70
dtype: int64

## SERIES ARITHMETIC

When you do arithmetic on two Series, Pandas automatically matches values by their index labels.

If a label exists in one Series but not the other, the result for that label will be NaN (Not a Number).
This is called index alignment.

In [27]:
s1 = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
s2 = pd.Series([5, 15, 25],  index=['A', 'B', 'D'])

# A matches A, B matches B
# C is only in s1 so result is NaN
# D is only in s2 so result is NaN
s1 + s2

A    15.0
B    35.0
C     NaN
D     NaN
dtype: float64

## CREATING A DATAFRAME FROM SCRATCH

You can create a DataFrame from a dictionary.
Each key becomes a column name and the list of values becomes the data for that column.

All lists must have the same length.

In [28]:
data = {
    'Student': ['Lahari', 'Pranav', 'Bharathi', 'Bannuru', 'Srikar', 'Teja', 'Vinay'],
    'Math':    [85, 92, 78, 95, 88, 81, 94],
    'Science': [90, 89, 85, 98, 80, 87, 92],
    'English': [95, 98, 90, 99, 92, 94, 89]
}

df = pd.DataFrame(data)
print(df)

    Student  Math  Science  English
0    Lahari    85       90       95
1    Pranav    92       89       98
2  Bharathi    78       85       90
3   Bannuru    95       98       99
4    Srikar    88       80       92
5      Teja    81       87       94
6     Vinay    94       92       89

## LOC AND ILOC

loc and iloc are two ways to select rows from a DataFrame.

loc  - selects rows based on the INDEX LABEL
iloc - selects rows based on the INTEGER POSITION (like a list index starting from 0)

When the index is the default (0, 1, 2...) both give the same result.
But when the index is custom (like names), they behave differently.

In [29]:
# loc - returns row with label 1
df.loc[1]

Student    Pranav
Math           92
Science        89
English        98
Name: 1, dtype: object

In [30]:
# iloc - returns the second row (position 1, 0-indexed)
df.iloc[1]

Student    Pranav
Math           92
Science        89
English        98
Name: 1, dtype: object

## ADDING A CALCULATED COLUMN

You can create a new column by doing calculations using existing columns.
The operation is done row by row automatically.

In [31]:
# calculate the average of Math and Science and store it in a new column
df['Average'] = (df['Math'] + df['Science']) / 2
df

    Student  Math  Science  English  Average
0    Lahari    85       90       95     87.5
1    Pranav    92       89       98     90.5
2  Bharathi    78       85       90     81.5
3   Bannuru    95       98       99     96.5
4    Srikar    88       80       92     84.0
5      Teja    81       87       94     84.0
6     Vinay    94       92       89     93.0

## BOOLEAN FILTERING

Boolean filtering lets you filter rows based on a condition.

When you write df['Math'] > 85, it returns a True/False value for each row.
When you pass that inside df[], it returns only the rows where the condition is True.

This is one of the most useful operations in Pandas.

In [32]:
# students scoring more than 85 in Math
df[df['Math'] > 85]

   Student  Math  Science  English  Average
1   Pranav    92       89       98     90.5
3  Bannuru    95       98       99     96.5
4   Srikar    88       80       92     84.0
6    Vinay    94       92       89     93.0

You can combine multiple conditions using & (AND) and | (OR).
Each condition must be wrapped in its own parentheses.

In [33]:
# multiple conditions - Math > 80 AND Science > 85
df[
    (df['Math'] > 80)
    &
    (df['Science'] > 85)
]

   Student  Math  Science  English  Average
0   Lahari    85       90       95     87.5
1   Pranav    92       89       98     90.5
3  Bannuru    95       98       99     96.5
5     Teja    81       87       94     84.0
6    Vinay    94       92       89     93.0

After filtering rows, you can also select only specific columns from the result.

In [34]:
# selecting specific columns after filtering
df[df['Math'] > 80][['Student', 'Math']]

   Student  Math
0   Lahari    85
1   Pranav    92
3  Bannuru    95
4   Srikar    88
5     Teja    81
6    Vinay    94

## INDEX OPERATIONS

Every DataFrame has an index - by default it is 0, 1, 2, 3...

reset_index() resets the index back to default integers.
The old index becomes a new column in the DataFrame.

If you don't want the old index as a column, pass drop=True.

set_index() lets you use one of the existing columns as the index.

In [35]:
# reset index - old index becomes a new column called 'index'
df.reset_index()

   index   Student  Math  Science  English  Average
0      0    Lahari    85       90       95     87.5
1      1    Pranav    92       89       98     90.5
2      2  Bharathi    78       85       90     81.5
3      3   Bannuru    95       98       99     96.5
4      4    Srikar    88       80       92     84.0
5      5      Teja    81       87       94     84.0
6      6     Vinay    94       92       89     93.0

In [36]:
# reset index and discard the old index completely
df.reset_index(drop=True)

    Student  Math  Science  English  Average
0    Lahari    85       90       95     87.5
1    Pranav    92       89       98     90.5
2  Bharathi    78       85       90     81.5
3   Bannuru    95       98       99     96.5
4    Srikar    88       80       92     84.0
5      Teja    81       87       94     84.0
6     Vinay    94       92       89     93.0

In [37]:
# set the Student column as the index
df.set_index('Student')

          Math  Science  English  Average
Student
Lahari      85       90       95     87.5
Pranav      92       89       98     90.5
Bharathi    78       85       90     81.5
Bannuru     95       98       99     96.5
Srikar      88       80       92     84.0
Teja        81       87       94     84.0
Vinay       94       92       89     93.0

## HANDLING MISSING VALUES

Real world data almost always has missing values. Pandas represents missing values as NaN (Not a Number).

We need to handle them before doing any analysis because NaN values can mess up calculations.

Two main ways to handle missing values:
1. dropna() - remove the rows or columns that have missing values
2. fillna() - fill the missing values with something (a number, mean, median etc)

In [38]:
# creating a dataframe with some missing values using np.nan
data = {
    'Student': ['Lahari', 'Pranav', 'Bharathi', 'Bannuru', 'Srikar', 'Teja', 'Vinay'],
    'Math':    [85, 92, 78, 95, 88, 81, np.nan],
    'Science': [90, 89, 85, np.nan, 80, 87, 92],
    'English': [95, np.nan, 90, 99, 92, np.nan, 89]
}

df = pd.DataFrame(data)
print(df)

    Student  Math  Science  English
0    Lahari  85.0     90.0     95.0
1    Pranav  92.0     89.0      NaN
2  Bharathi  78.0     85.0     90.0
3   Bannuru  95.0      NaN     99.0
4    Srikar  88.0     80.0     92.0
5      Teja  81.0     87.0      NaN
6     Vinay   NaN     92.0     89.0

## DROPNA

dropna() by default removes any row that has at least one missing value.
Only rows having no missing values at all will remain.

In [39]:
# removes rows with any missing values
df.dropna()

    Student  Math  Science  English
0    Lahari  85.0     90.0     95.0
2  Bharathi  78.0     85.0     90.0
4    Srikar  88.0     80.0     92.0

axis=1 means you are applying the operation on columns instead of rows.
So dropna(axis=1) drops any column that has even one missing value.

In [40]:
# axis=1 means columns - drops columns that have any null value
df.dropna(axis=1)

    Student
0    Lahari
1    Pranav
2  Bharathi
3   Bannuru
4    Srikar
5      Teja
6     Vinay

thresh parameter lets you control how many non-null values a row must have to be kept.
For example thresh=3 means keep only rows that have at least 3 non-null values.

In [41]:
# thresh=3 means keep rows that have minimum 3 non-null values
df.dropna(thresh=3)

    Student  Math  Science  English
0    Lahari  85.0     90.0     95.0
1    Pranav  92.0     89.0      NaN
2  Bharathi  78.0     85.0     90.0
3   Bannuru  95.0      NaN     99.0
4    Srikar  88.0     80.0     92.0
5      Teja  81.0     87.0      NaN
6     Vinay   NaN     92.0     89.0

## FILLNA

fillna() fills missing values instead of removing them.
You can fill with a constant value like 0 or a string like 'Not Available'.

A smarter approach is to fill with the mean or median of that column so you dont distort the data too much.

In [42]:
# fill all missing values with a constant string
df.fillna('Not Available')

    Student           Math        Science        English
0    Lahari           85.0           90.0           95.0
1    Pranav           92.0           89.0  Not Available
2  Bharathi           78.0           85.0           90.0
3   Bannuru           95.0  Not Available           99.0
4    Srikar           88.0           80.0           92.0
5      Teja           81.0           87.0  Not Available
6     Vinay  Not Available           92.0           89.0

In [43]:
# fill missing marks in English with the average English marks
df['English'].fillna(
    df['English'].mean()
)

0    95.0
1    93.0
2    90.0
3    99.0
4    92.0
5    93.0
6    89.0
Name: English, dtype: float64

## GROUPBY

groupby() is used to group rows together based on the values in a column, and then apply an aggregation on each group.

Think of it like this - if you have student data with departments, groupby('Department') will split the data into separate groups for each department. Then you can calculate the average, sum, max etc. for each group.

The logic is:
1. Split the data into groups
2. Apply a function (mean, sum, count etc)
3. Combine the results

In [44]:
students = pd.DataFrame({
    'Student':     ['Lahari', 'Pranav', 'Bharathi', 'Bannuru', 'Srikar', 'Teja', 'Vinay'],
    'Department':  ['Math', 'Biology', 'Math', 'English', 'Math', 'Biology', 'English'],
    'Total_Marks': [750, 650, 820, 680, 700, 780, 840]
})

In [45]:
# groupby alone just creates a GroupBy object, nothing is shown yet
students.groupby('Department')

In [46]:
# average marks by department
students.groupby('Department').mean(numeric_only=True)

            Total_Marks
Department
Biology      715.000000
English      760.000000
Math         756.666667

In [47]:
# total marks by department
students.groupby('Department').sum(numeric_only=True)

            Total_Marks
Department
Biology            1430
English            1520
Math               2270

In [48]:
# maximum marks by department
students.groupby('Department').max(numeric_only=True)

            Total_Marks
Department
Biology             780
English             840
Math                820

In [49]:
# count of students in each department
students.groupby('Department').count()

            Student  Total_Marks
Department
Biology           2            2
English           2            2
Math              3            3

## CONCAT

concat is used to combine two or more DataFrames together.

By default it stacks them vertically (one below the other). This is useful when you have data split across multiple files or batches.

With axis=1 it stacks them horizontally (side by side as new columns). This is useful when you want to add new columns to a DataFrame.

In [50]:
team1 = pd.DataFrame({
    'student':    ['Lahari', 'Pranav', 'Teja'],
    'Total_Marks':[750, 650, 780]
})

In [ ]:
team2 = pd.DataFrame({
    'student':    ['Bharathi', 'Srikar', 'Vinay', 'Bannuru'],
    'Total_Marks':[820, 700, 840, 680]
})

In [ ]:
# stacking vertically - one below the other
# notice the index still shows original values (0,1,2 repeated)
pd.concat([team1, team2])

In [ ]:
# stacking horizontally - side by side as new columns
dept = pd.DataFrame({
    'Department': ['Math', 'Biology', 'English']
})

pd.concat([team1, dept], axis=1)

## MERGE - JOINING DATAFRAMES

merge is used to join two DataFrames based on a common column. It works exactly like SQL joins.

The 'on' parameter tells which column to use for matching.
The 'how' parameter tells what type of join to do.

Types of joins:

inner  - keeps only rows where the key exists in BOTH DataFrames
left   - keeps all rows from the left DataFrame, and only matching rows from the right. Non-matching rows from right get NaN
right  - keeps all rows from the right DataFrame, and only matching rows from the left. Non-matching rows from left get NaN
outer  - keeps all rows from BOTH DataFrames. NaN where there is no match on either side

In [ ]:
students1 = pd.DataFrame({
    'studID':  [1, 2, 3],
    'student': ['Lahari', 'Pranav', 'Teja']
})

In [ ]:
students2 = pd.DataFrame({
    'studID':      [1, 2, 4],
    'Total_Marks': [750, 650, 780]
})

In [ ]:
# inner join - only studID 1 and 2 are common in both, so only they appear
pd.merge(
    students1,
    students2,
    how='inner',
    on='studID'
)

In [ ]:
# left join - all rows from students1 are kept
# studID 3 (Teja) exists in students1 but not in students2, so Total_Marks is NaN
pd.merge(
    students1,
    students2,
    how='left',
    on='studID'
)

In [ ]:
# right join - all rows from students2 are kept
# studID 4 exists in students2 but not in students1, so student name is NaN
pd.merge(
    students1,
    students2,
    how='right',
    on='studID'
)

In [ ]:
# outer join - all rows from both DataFrames are kept
# NaN appears wherever there is no match
pd.merge(
    students1,
    students2,
    how='outer',
    on='studID'
)

## SUMMARY OF EVERYTHING COVERED TODAY

pd.read_csv()           - load a CSV file
df.head() / df.tail()   - see first or last n rows
df.shape                - get rows and columns count
df.columns              - get all column names
df.dtypes               - get data types of all columns
df.describe()           - statistical summary
df['col']               - select one column
df[['col1','col2']]     - select multiple columns
df['col'].unique()      - get all unique values
df.isnull().sum()       - count null values per column
df['col'] = value       - add a new column
pd.Series()             - create a 1D labeled array
df.loc[]                - select row by label
df.iloc[]               - select row by position
df[condition]           - filter rows with boolean condition
df.reset_index()        - reset index to default integers
df.set_index('col')     - set a column as the index
df.dropna()             - remove rows with null values
df.fillna(value)        - fill null values with something
df.groupby('col').mean()- group and aggregate
pd.concat([df1, df2])   - stack DataFrames together
pd.merge(df1, df2)      - join DataFrames on a common column